Added YAML Parser
GameEngineDesign-S24/AstraEngine pull request #19
Opened 2024-05-21 22:03 UTC by maxwaldman8

2024-05-21 22:17 UTC, jcollard requested changes
You should provide unit tests showing how to use this as well as a use case in the `AstraEngine.Examples`.

2024-05-21 22:17 UTC, jcollard commented on AstraEngine.Serialization/AstraEngine.Serialization.csproj
> +    <OutputType>Exe</OutputType>
This should not produce an executable. You should remove this line.

2024-05-21 22:17 UTC, jcollard commented on AstraEngine.Serialization/AstraEngine.Serialization.csproj
> +  <PropertyGroup>
@maxwaldman8 
When you intend other people to use your code as a library, you should include this line in the `<PropertyGroup>` section: `<GenerateDocumentationFile>true</GenerateDocumentationFile>`.

You can see this here:

https://github.com/maxwaldman8/AstraEngine/blob/3-Feature-Request-YAML-Parser/AstraEngine.InputSystem/AstraEngine.InputSystem.csproj

```xml
﻿<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
```

2024-05-21 22:17 UTC, jcollard commented on AstraEngine.Serialization/Parser.cs
> +public class Parser {
@maxwaldman8  I'd recommend making this a static class.

2024-05-21 22:17 UTC, jcollard commented on AstraEngine.Serialization/Parser.cs
> +        } catch {
It is typically bad practice to not specify the exception type. What exception are you expecting to catch here?

2024-06-03 17:03 UTC, jcollard requested changes
A Herculean effort here! 

Some small things to fix / consider before this is merged.

2024-06-03 17:19 UTC, maxwaldman8 commented on AstraEngine.Core/Component.cs
> +    public void Start()
Shouldn't this change (and the other ones below this) be for my other pull request? I am not sure why they appeared as changed files on this one.

2024-06-03 17:24 UTC, jcollard commented on AstraEngine.Core/Component.cs
> +    public void Start()
You may need to merge `GameEngineDesign-S24:main` into your branch.

2024-06-05 19:28 UTC, jcollard reviewed
I'm not sure remove Initialize from Tick is the best thing to do. Let's talk about it first.

2024-06-05 19:28 UTC, jcollard commented on AstraEngine.Core/Entity.cs
> +            child.Initialize();
What do you do if the parent is not active when the child is added? What if the child being added is not active?

2024-06-10 15:55 UTC, jcollard approved these changes
Looking good! Fantastic effort @maxwaldman8

2024-06-10 15:55 UTC, merged